services:
  db:
    image: postgres:17-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/master_db_init.sql
    environment:
      - POSTGRES_PASSWORD=Password1!
      - POSTGRES_DB=library_system_db
    ports:
      - "5432:5432"

volumes:
  pgdata: