spring:
  security:
    user:
      name: user
      password: d821eed2-1033-4572-a3b8-edd4fcb531a9

  application:
    name: library-system

  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      schema: ${SPRING_DATASOURCE_SCHEMA}

  jpa:
    hibernate:
      ddl-auto: none

  data:
    web:
      pageable:
        one-indexed-parameters: true

  flyway:
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    schemas: ${SPRING_DATASOURCE_SCHEMA}
    locations: classpath:db/migration

firebase:
  service-account-key-path: classpath:firebase-adminsdk.json